---
title: "Step 3 – Apply for a UPPMAX Account"
format:
  html:
    toc: true
---

# Apply for a UPPMAX Account

Once your project has been approved in SUPR, your allocation on **Gorilla**, **Pelle**, and/or **Lutra** becomes active.  
To log in to these systems, you must also have a **UPPMAX user account**. This account is separate from SUPR and is required for accessing the compute clusters operated by UPPMAX.

## Why You Need a UPPMAX Account

The UPPMAX systems (Gorilla, Pelle, Lutra) are operated by Uppsala University.  

SUPR is used to manage the resources applications and allocations, but you still need a local UPPMAX user account so you can:

- log in via SSH  
- access project directories  
- run jobs on the clusters  
- use software modules and storage areas  

## How to Apply for a UPPMAX Account


1. Log into SUPR here: <https://supr.naiss.se>, using the same identity you used for SUPR.  
2. In the left hand menu, click `Accounts`.  
3. Under the heading `Account Requests`, you should find the project that got approved. 
4. Click `Request account`.

**[MORE INFO NEEDED]**

## Approval and Activation

- UPPMAX staff will approve your request and create your user account.  
- Once created, you will receive an email with login details (including your username).  
- After activation, you can log in to Gorilla, Pelle, or Lutra immediately.

## After You Have Your Account

When your UPPMAX account is active, you can:

- connect to the clusters via SSH  
- access your project directory  
- start running jobs and workflows  
- use software modules and storage areas  
- monitor resource usage

Click below for a shoer summary of how to log on and work on the servers. 

<a class="btn btn-primary w-100" role="button" style="padding: 1rem; font-size: 1.1rem;" href="apply-step4.qmd">Step 4: Access after Approval</a>

---

For questions or problems with your UPPMAX account, contact:  
**support@slu.se**
