---
title: "Step 1 – Apply for a NAISS/SUPR Account"
format:
  html:
    toc: true
---

## UPPMAX

UPPMAX (Uppsala Multidisciplinary Center for Advanced Computational Science) is the local NAISS centre at Uppsala University that operates the systems you can apply to in SLU Local Round.

To request compute and storage resources at UPPMAX, you must first have an active user account in the NAISS/SUPR system.

## What is NAISS/SUPR?

NAISS (National Academic Infrastructure for Supercomputing in Sweden) provides national high-performance computing and storage resources.  

SUPR/NAISS is the web portal used to manage:

- user accounts  
- project applications  
- resource allocations  

You access SUPR here: <https://supr.naiss.se>

## Who Can Apply?

- Employees and researchers at SLU can apply to get resources via the SLU round. 

## Create a SUPR Account

1. Fill out & submit [account request form](https://supr.naiss.se/person/register/).

::: {.callout-tip}
- If possible, use `Register with Federated Identity`.
- If this option doesn't work for you, use instead `Register without Federated Identity`.
:::

2. Fill in your contact details and affiliation with **Sveriges lantbruksuniversitet**.  
3. Confirm your email address if requested.

::: {.callout-tip}

When registering or updating your profile:

- Select **Sveriges lantbruksuniversitet** as your organisation.  
- Add your research group, department or unit in the profile description if relevant.  

This makes it easier to link you to the correct projects and allocations.
:::

## Accept NAISS user agreement

Just after creating the SUPR account, on the page you are taken to, there will be a section titled “User Agreement” at the very top. Just under it is the button named “Accept NAISS User Agreement”. 

Alternately, if you do this at a later point. Login to SUPR. At the very top it will say “NAISS User Agreement Pending”.

::: {.callout-tip}
- If possible, use the `With SWAMID` option - **this is much faster!**
- Alternatively, use `Alternative: Offline via Paper Form`. Here you will have to print out, sign and send in the form. **This may take up to a week. **
:::

## After Your Account Is Created

Once your SUPR account is active, you can:

- be added as a member to existing projects, and  
- submit new applications in calls such as **“SLU Local 2026”**.

Continue to see how to apply for compute and storage resources:

<a class="btn btn-primary w-100" role="button" style="padding: 1rem; font-size: 1.1rem;" href="apply-step2.qmd">Step 2: Apply for Resources via \"SLU Local 2026\"</a>


---

For questions or problems with registration, contact:  
**support@slu.se**
